### ISSUE TITLE
Investigate WSO2 IoT platform

### ISSUE THREAD

**Issue by Quoc-Huy-Nguyen** [msep2019/MSEP_2019_2#17]
Install the platform on VM
Run tests on VM

**Comment by Quoc-Huy-Nguyen** [comment]
Please leave the comments about the supported protocols, used databases, security features, and APIs for connecting and sending messages.

**Comment by conglincolin** [comment]
Installed the IOT platform on VM successfully.
Next : MOTT configuration， run test

**Comment by conglincolin** [comment]
MQTT installed and tested successfully. The issue is that do not find out an approach to create the connection between MQTT and WSO2 for Ubuntu. The tutorial is for windows OS.

**Comment by conglincolin** [comment]
Give up the WSO2 for Ubuntu, make comparison with other IoT platforms which have tried to configured and tested.
