### ISSUE TITLE
Implement events in smart contract

### ISSUE THREAD

**Issue by Quoc-Huy-Nguyen** [msep2019/MSEP_2019_2#49]
Implement events in smart contract, allow contracts for firing events after completing some tasks
Requirements:
- Create a new event in smart contract using Solidity
- Deploy that smart contract to blockchain network
- Call the function that fire events
- Verify results by using Truffle console/Ganache GUI

**Comment by Quoc-Huy-Nguyen** [comment]
- Add SimpleEvent in the SimpleContract, and emit this event [emit_event](https://github.com/msep2019/MSEP_2019_2/commit/831df0300e15ccdc872f181c1026879268dafb25)
- Deploy smart contract by using truffle command: npx truffle migrate
- Call the calculate() function to do some calculations and emit an event.  This event will be caught by observer, that observer will get the datastream name from IoT APIs and send result back to smart contract using Truffle console:
- npx truffle console
- In truffle console run following commands:
+ var dApp
+ SimpleContract.deployed().then(function(instance) { dApp = instance; })
+ dApp.calculate(0,1)
+ dApp.datastream.call() (to verify the result)

**Comment by conglincolin** [comment]
Add "event Instructor(uint256 a, uint256 b);" to the smart contract, and emit the event in the function 'MyNewContract'

Deploy the smart contract via truffle command

Utilised the console by using 'MyContract.deployed().then(instance => {dApp = instance})
' and ' dApp.MyNewContract(4,6) ' to emit the event and catch the event
