### ISSUE TITLE
Implement services for listening events from blockchain

### ISSUE THREAD

**Issue by Quoc-Huy-Nguyen** [msep2019/MSEP_2019_2#50]
Implement services for listening events from blockchain.
* Requirements:
- Write service(s) listening to events from blockchain using NodeJS and web3 module.
- The service catch events fired by the deployed smart contracts, execute its functional tasks and send the result back to smart contracts.
- Verify the state of smart contracts by using Truffle console/Ganache GUI

**Comment by Quoc-Huy-Nguyen** [comment]
1. Implement the event listener project [event_listener](https://github.com/msep2019/MSEP_2019_2/commit/831df0300e15ccdc872f181c1026879268dafb25) that listen to SimpleEvent fired from SimpleContract.
2. This service catch the event, call the API server and get the first datastream name then send back to SimpleContract by using the function storeDatastream to update the datastream variable in SimpleContract
`const simpleContract = new web3.eth.Contract(tokenInterface.abi, deployedAddress)
simpleContract.events.SimpleEvent()
    .on('data', (event) => {
        console.log(event);
        request('http://34.67.130.25:5000/req/datastreams', { json: true }, (err, res, body) => {
            if (err) { return console.log(err); }
            console.log(body[0]);
            // Call contract method to store datastream name
            simpleContract.methods.storeDatastream(body[0].name).send({from: '0x475cC82cFb4e27d7f0aeCE782e707Acb489d8BF7' });
        });
    })
    .on('error', console.error); `

3. Using command: dApp.datastream.call() in Truffle console to verify the result

**Comment by conglincolin** [comment]
Implement the event listener via JS

const Web3 = require('web3');
const fs = require('fs');
//if (typeof Web3 !== 'undefined') { 
//    const web3T = new Web3(Web3.currentProvider); 
//} else { 
//    const webhttp = new Web3(Web3.givenProviders || new Web3.providers.HttpProvider('http://127.0.0.1:7545'));
//}
//const webhttp = new Web3(Web3.givenProviders || new Web3.providers.HttpProvider('http://127.0.0.1:7545'));
const websocket = new Web3(Web3.givenProviders || new Web3.providers.WebsocketProvider('http://127.0.0.1:7545'));

const mycontractJson = require('/Users/conglin/blockchain/truffle_sample/build/contracts/Mycontract.json');
const contractDetail = {
    abi : mycontractJson.abi,
    contractAddress : '0xDC0AfDc52683df220937739D1Fdfd11E4345eFeA'
};

//let MyContract;
//let Migrations;

// function mycontractListen(){
const myContract = new websocket.eth.Contract(contractDetail.abi, contractDetail.contractAddress);
    
// }
console.log("-------");
    myContract.events.Instructor().on('data', (event) =>{
        const data = event.returnvalues;
        data.hash_id, { 
            'a': data.a,
            'b': data.b,
        };
    })
    .on('error', function(err){
        console.log(err);
    });

//mycontractListen();
