### ISSUE TITLE
Setup LIT Core project on the private blockchain network

### ISSUE THREAD

**Issue by Quoc-Huy-Nguyen** [msep2019/MSEP_2019_2#51]
Setup LIT Core project on the private blockchain network
* Requirements:
- Clone the project LIT core: https://github.com/nguyentran0212/LIT/tree/master/LIT_core to local machine
- Deploy smart contracts: LIT and TestSite to local Ganache using Truffle
- Verify results on Ganache: LIT contract can interact with the TestSite contract.

**Comment by Quoc-Huy-Nguyen** [comment]
1. Clone project to local repository by using git clone command
2. Deploy LIT core smart contracts using command: npx truffle migrate
3. Verify on the Ganache

**Comment by conglincolin** [comment]
Clone the project to local repository and deploy it with truffle command line.
Inspect via Ganache
