### ISSUE TITLE
Setup LIT_frontend project for submitting experiments

### ISSUE THREAD

**Issue by Quoc-Huy-Nguyen** [msep2019/MSEP_2019_2#52]
Setup LIT_frontend project for submitting experiments
https://github.com/nguyentran0212/LIT/tree/master/LIT_frontend

**Requirements:**
- Clone from GitHub and deploy this project on local machine 
- Submit a experiment using this service
- Verify that the LIT contract receive this experiment and send to the TestSite contract.
- Verify that the content of this experiment is correct on the LIT middleware service.

**Comment by Quoc-Huy-Nguyen** [comment]
1. Clone the project by using git clone command
2. Update the configuration in file config_frontend.json to match with the local Ganache configuration
3. Start this service by using command : npx lite-server 
4. Create a new experiment with code: grafana/grafana
5. Access the link: http://127.0.0.1:3000 to check whether Grafana is running or not.

**Comment by conglincolin** [comment]
**Clone the project to the local

Modify the config_frontend.json to match the Ganache**

{
    "addrLIT" : "0xDC0AfDc52683df220937739D1Fdfd11E4345eFeA",
    "creatorAcc" : "0x28Ef510fbCfdbf87bC35ec8D67956b67Fd42b6EA"
}

**Install npx and start the lite-server**

**Create a new experiment and inspect the console of the Chrome**
