### ISSUE TITLE
Setup LIT middleware project

### ISSUE THREAD

**Issue by Quoc-Huy-Nguyen** [msep2019/MSEP_2019_2#53]
Setup LIT middleware project
https://github.com/nguyentran0212/LIT/tree/master/LIT_MW

**Requirements**
- Clone from GitHub and deploy this project on local machine 
- Verify that the content of experiments are correct during the execution of this middleware service.
- Use Docker compose instead of Docker to deploy a Docker image
- Collect performance data of Docker images and send back to TestSite contract.

**Comment by Quoc-Huy-Nguyen** [comment]
1. Clone project by using git clone command
2. Update configuration in file mw-config.json to match with Ganache's configuration
3. Start this service by using command: node TestSiteBootstrapper.js
4. Verify the experiment code by using console.log function 
5. Use Docker commands to pull and start an instance in file: TestSiteDaemon.js
6. Collect Docker's images statistics (in progress)

**Comment by conglincolin** [comment]
**Clone the project**

**Modify the mw-config.json to match the local Ganache**

{
    "ownerAcc" : "0xb60f52941f9ab1381ee5DC5a9861FFCDd88B0171",
    "addrTestSite" : "",
    "addrLIT" : "0xDC0AfDc52683df220937739D1Fdfd11E4345eFeA",
    "addrRPC" : "HTTP://127.0.0.1:7545",
    "addrContractArtifact" : "./"
}
**Execute the TestSiteBootstrapper.js. While executing the frontend via creating a new experiment to check the results**

**Use Docker compose instead of Docker to deploy a Docker image (in progress)**

**Collect performance data of Docker images and send back to TestSite contract (in progress)**

**Comment by Quoc-Huy-Nguyen** [comment]
Add docker-compose module into LIT middleware project. Using docker-compose to start services specified in experiment's code. The experiment code is stored in a folder named with the experiment id.
for example: ./experiments/0x4f9f8e266157990add6a1de4cef397001bb5f671/docker-compose.yml

**Comment by Quoc-Huy-Nguyen** [comment]
Move the part of collecting image performance to next sprint and close the issue.
