### ISSUE TITLE
Investigate  docker and docker compose used in a NodeJS project

### ISSUE THREAD

**Issue by Quoc-Huy-Nguyen** [msep2019/MSEP_2019_2#54]
Investigate  docker and docker compose used in a NodeJS project. 
 Requirements:
- Install the NodeJS docker compose module.
- Run the docker-compose command in NodeJS
- Verify the services are correctly deployed and accessible.

**Comment by conglincolin** [comment]
1. Install docker compose module with command line: npm install -save docker-compose
2. Install docker hub and login in on the laptop
Set up a docker-compose.yml file

version: '3'
services:
  web:
    image: "colin120/docker-test"
    ports:
      - "3000:3000"

Set up a nodeJs file with the code to run docker compose

const DockerCompose = require('docker-compose');
DockerCompose.upAll({ cwd: '.', log: true })
  .then(
    () => { console.log('done')},
    err => { console.log('something went wrong:', err.message)}
  );

Run the nodeJS file with command line to test the docker

3. Verify the docker with port 3000
    Before testing, run command line: lsof -i :3000, check whether the port is occupied.
    If the port is occupied, kill it before test the docker.
    Use the port to run the docker with 3000
    Or use command line: docker cantainer ps to check which docker is running
