### ISSUE TITLE
Integrate docker-compose library into LIT middleware project

### ISSUE THREAD

**Issue by Quoc-Huy-Nguyen** [msep2019/MSEP_2019_2#59]
Integrate docker-compose library into LIT middleware project
Requirements:
- Add docker-compose module into LIT middleware project
- Successfully deploy user docker-compose code on IoT Testbed server
- Return the appropriate result after deploying. For example: success or fail, the generated log (if necessary)

**Comment by conglincolin** [comment]
1. Create a docker and upload to the docker hub, add the docker compose code with nodeJS to the TestSiteDaemon.js

2. Run the server and frontend, create an experiment with docker-compose.yml
3. Run the TestSiteDaemon.js, when creating the experiment, check the returned result and the experiment folder. First check whether the corresponding folder has saved the docker-compose.yml successfully. Second, check whether the "done" has returned which means the docker should be running. And it can be executed successfully via port on the browser
