### ISSUE TITLE
Create a customized Docker image for service created in issue #66

### ISSUE THREAD

**Issue by Quoc-Huy-Nguyen** [msep2019/MSEP_2019_2#67]
Create a customized Docker image for service created in issue #66
User can experience this image through LIT frontend website.

**Comment by conglincolin** [comment]
Customised Docker image of Grafana to collect and visualise the sensor data, the Grafana will connect the Influxdb.

Upload the Docker image to Docker hub.

**Comment by Quoc-Huy-Nguyen** [comment]
Create a Docker image for weather-station project and upload to Docker hub: repository: 
rossiweasel/weather-station, tag: initial
